@url = http://localhost:4000/api/posts
@content = application/json

// GET Requests

GET {{url}}

###

GET {{url}}/1

###

GET {{url}}/7/comments

###

// End GET Requests
// POST Requests

POST {{url}}/1/comments
Content-Type: {{content}}

{
	"text": "This is some voodoo shizz"
}

// End POST Requests